### ISSUE TITLE
Lazy macro loading seems to be breaking on Julia v1.9.0-rc1

### ISSUE THREAD

**Issue by singularitti** [wangl-cc/LazyStartup.jl#11]
I am trying this in my `startup.jl`:

```julia
@lazy_startup using Unitful @u_str
```

But it does not seem to be loaded on Julia v1.9+.

```julia
Julia Version 1.9.0-rc1
Commit 3b2e0d8fbc1 (2023-03-07 07:51 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by wangl-cc** [comment]
Hey, I can't reproduce it.
```julia
julia> versioninfo()
Julia Version 1.9.0-rc1
Commit 3b2e0d8fbc1 (2023-03-07 07:51 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores

julia> isdefined(Main, :Unitful)
false

julia> u"m"
m

julia> isdefined(Main, :Unitful)
true
```

**Comment by singularitti** [comment]
OK, it seems to be happening since I have the following lines in my `startup.jl`:

```julia
using REPL
atreplinit() do repl
    if !isdefined(repl, :interface)
        repl.interface = REPL.setup_interface(repl)
    end
    REPL.ipython_mode!(repl)
end
```

This is the IPython mode that v1.9 introduced (see https://github.com/JuliaLang/julia/pull/46474). It may change the environment in REPL. I tried to put these lines before `using LazyStartup: @lazy_startup`, but no effect.

**Comment by singularitti** [comment]
I have met a similar issue before, maybe this link will help: https://github.com/KristofferC/OhMyREPL.jl/pull/279

**Comment by wangl-cc** [comment]
Thanks, I will look into it later.

**Comment by wangl-cc** [comment]
I believe that the reason for the issue is due to the `ipython_mode` which breaks the ability to load a package and using macros provided by that package in a single input line in the REPL. See JuliaLang/julia#49041.

**Comment by singularitti** [comment]
It works for me, thank you!
